# secrets.py - Fake secrets for testing secret scanning

# Fake API key
API_KEY = "12345678-abcdefg-12345-6789abc"

# Fake password
DB_PASSWORD = "supersecretpassword123"

# Fake AWS key
AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

# Fake OAuth token
OAUTH_TOKEN = "ya29.a0AfH6SMDGsC9GkDphdFpy5gD73Xj3Vjdwoiyc_olFxLmj8d3XjEjSHK7"
